services:
  - name: backend
    buildCommand: npm run build
    startCommand: npm start
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: YourDatabaseName
          query: "SELECT connection_string FROM YourTable WHERE id = 'YourId'"
